"""ElevenLabs Agents platform adapter (runs alongside the Fonio routes).

Endpoints (mounted under /elevenlabs by main.py):
  POST /elevenlabs/call-init   conversation-initiation webhook: caller lookup
                               on ring, returned as dynamic variables. Auth:
                               the same Bearer WEBHOOK_SECRET as Fonio, set as
                               a workspace-secret header in the EL dashboard.
  POST /elevenlabs/post-call   post-call webhook: ONE protocol ticket per
                               call via log_call_core. Auth: HMAC signature
                               (ElevenLabs-Signature header) — fail-closed
                               503 while ELEVENLABS_POST_CALL_HMAC_SECRET is
                               unset, since this endpoint WRITES tickets.

The mid-call tools (verify_caller / create_request) are NOT adapted here —
ElevenLabs server tools point directly at the existing /verify-caller and
/create-request, so the §10.1 failure bodies stay byte-identical across
platforms and every server-side order control applies unchanged.

Security deltas vs the Fonio /lookup-caller contract (deliberate):
  - date_of_birth is never emitted (verification secret, server-checked);
  - customer_number is only an empty seed — the real value enters the
    conversation exclusively via the verify_caller tool assignment;
  - postal_code is not defined AT ALL as a dynamic variable: on Fonio it
    rides along unspoken (pure exfiltration surface for prompt injection);
    the PLZ factor is caller-spoken and checked server-side, so the new
    platform closes that gap.
Absent values are sent as "" (ElevenLabs' null support is undocumented);
permission_to_order_again is the string tri-state "true"/"false"/"unknown".
The agent prompt documents both conventions.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import threading
import time
from collections import OrderedDict

from fastapi import APIRouter, Header, HTTPException, Request
from pydantic import BaseModel
from starlette.concurrency import run_in_threadpool

from call_flows import CallerOut, CallLogOut, _check_auth, log_call_core, lookup_caller_core

log = logging.getLogger("fonio-bc")

router = APIRouter(prefix="/elevenlabs")

# HMAC secret for the post-call webhook — generated by ElevenLabs when the
# webhook is created. REQUIRED for /elevenlabs/post-call (fail-closed 503,
# see the endpoint). Read at import time like all other config.
ELEVENLABS_POST_CALL_HMAC_SECRET = os.environ.get("ELEVENLABS_POST_CALL_HMAC_SECRET")

# Agent ids whose calls are filed as [TEST]/internal — the EL-side equivalent
# of Fonio's static internal=true tool field (test-ness must never be
# LLM-controlled). Keep the rollout agent listed here until go-live.
ELEVENLABS_TEST_AGENT_IDS = {
    a.strip()
    for a in os.environ.get("ELEVENLABS_TEST_AGENT_IDS", "").split(",")
    if a.strip()
}


class CallInitIn(BaseModel):
    """Documented initiation payload. All fields tolerant-optional: anonymous
    callers (suppressed caller ID) arrive without a usable caller_id and must
    still get a well-formed no-match variable set."""

    caller_id: str | None = None
    agent_id: str | None = None
    called_number: str | None = None
    call_sid: str | None = None


def _dynamic_variables(c: CallerOut) -> dict[str, object]:
    """CallerOut -> the FULL dynamic-variable set. ElevenLabs requires every
    agent-defined variable in every response, so this is one unconditional
    dict — no key may become conditional. customer_number / verified /
    last_request_number are seeds maintained mid-call by tool assignments."""
    perm = c.permission_to_order_again
    return {
        "customer_found": c.customer_found,
        "name": c.name or "",
        "phone_number": c.phone_number or "",
        "permission_to_order_again": (
            "unknown" if perm is None else ("true" if perm else "false")
        ),
        "last_ordered_items": c.last_ordered_items or "",
        "last_order_date": c.last_order_date or "",
        "max_quantity": c.max_quantity,
        "contact_no": c.contact_no or "",
        "customer_number": "",
        "verified": "",
        "last_request_number": "",
        # 2026-08-28: same tri-state encoding as permission_to_order_again.
        "patient_is_minor": _tri(c.patient_is_minor),
        "dob_on_file": _tri(c.dob_on_file),
    }


def _tri(value: bool | None) -> str:
    return "unknown" if value is None else ("true" if value else "false")


@router.post("/call-init")
def call_init(
    body: CallInitIn,
    authorization: str | None = Header(default=None),
) -> dict[str, object]:
    """Conversation-initiation webhook: same lookup as /lookup-caller, wrapped
    in the ElevenLabs envelope. No conversation_config_override — the dashboard
    stays the single source of agent configuration."""
    _check_auth(authorization)
    caller = lookup_caller_core(body.caller_id)
    return {
        "type": "conversation_initiation_client_data",
        "dynamic_variables": _dynamic_variables(caller),
    }


def verify_elevenlabs_signature(
    raw: bytes,
    header: str | None,
    *,
    secret: str,
    now: float | None = None,
    tolerance_s: int = 1800,
) -> bool:
    """Check an `ElevenLabs-Signature: t=<unix_ts>,v0=<hex>` header.

    HMAC-SHA256 over b"{t}.{raw}" with the shared secret; the timestamp must
    be within the 30-minute documented tolerance (small forward skew allowed).
    Multiple v0 entries are accepted (secret rotation); comparison is
    constant-time. Returns False on ANY parse problem — callers answer one
    generic 401 and log the specific reason server-side only."""
    if not header or not secret:
        return False
    t: str | None = None
    v0s: list[str] = []
    for part in header.split(","):
        key, sep, value = part.strip().partition("=")
        if not sep:
            return False
        if key == "t":
            t = value
        elif key == "v0":
            v0s.append(value)
    if t is None or not v0s:
        return False
    try:
        ts = int(t)
    except ValueError:
        return False
    now = time.time() if now is None else now
    if not (now - tolerance_s <= ts <= now + 300):
        return False
    mac = hmac.new(secret.encode(), f"{t}.".encode() + raw, hashlib.sha256).hexdigest()
    return any(hmac.compare_digest(mac, v) for v in v0s)


# Bounded replay cache: ElevenLabs retries post_call_transcription on
# 5xx/429/408 AND on a lost 200 — the latter would duplicate the protocol
# ticket. Maps conversation_id -> the response already returned. In-process
# only (a restart during the retry window costs at most one duplicate
# protocol ticket — no order side effects; accepted).
_DEDUP_MAX = 512
_dedup_lock = threading.Lock()
_dedup: OrderedDict[str, CallLogOut] = OrderedDict()


def _dedup_get(conversation_id: str) -> CallLogOut | None:
    with _dedup_lock:
        result = _dedup.get(conversation_id)
        if result is not None:
            _dedup.move_to_end(conversation_id)
        return result


def _dedup_put(conversation_id: str, result: CallLogOut) -> None:
    with _dedup_lock:
        _dedup[conversation_id] = result
        _dedup.move_to_end(conversation_id)
        while len(_dedup) > _DEDUP_MAX:
            _dedup.popitem(last=False)


def _first_nonempty(*values: object) -> str | None:
    for v in values:
        if isinstance(v, str):
            v = v.strip()
        if v:
            return str(v)
    return None


def _tri_state(value: object) -> bool | None:
    """true/false/"" (the seed) -> True/False/None — keeps the protocol
    ticket's "nicht geprüft" state despite the empty-string seed."""
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        s = value.strip().lower()
        if s == "true":
            return True
        if s == "false":
            return False
    return None


def _log_call_kwargs(data: dict) -> dict[str, object]:
    """Map the fixed post_call_transcription payload onto log_call_core.

    Authoritative facts (verified, contact_no, customer state) come from the
    dynamic-variables echo — they were written server-side by the tool
    assignments during the call. Free-text/accumulative fields lean on the
    agent's analysis (transcript_summary, data_collection_results)."""
    dv = (
        (data.get("conversation_initiation_client_data") or {}).get("dynamic_variables")
        or {}
    )
    analysis = data.get("analysis") or {}
    dcr = analysis.get("data_collection_results") or {}
    metadata = data.get("metadata") or {}
    conversation_id = data.get("conversation_id")

    eligibility = _first_nonempty(dv.get("permission_to_order_again"))
    if eligibility == "unknown":
        eligibility = "unbekannt"

    return {
        "phone_number": _first_nonempty(
            dv.get("system__caller_id"),
            dv.get("phone_number"),
            (metadata.get("phone_call") or {}).get("external_number"),
        ),
        "name": _first_nonempty(dv.get("name")),
        "summary": _first_nonempty(analysis.get("transcript_summary")),
        "contact_no": _first_nonempty(dv.get("contact_no")),
        "bc_found": _tri_state(dv.get("customer_found")),
        "verified": _tri_state(dv.get("verified")),
        "request_numbers": _first_nonempty(
            (dcr.get("request_numbers") or {}).get("value"),
            dv.get("last_request_number"),
        ),
        "requested_items": _first_nonempty(
            (dcr.get("requested_items") or {}).get("value")
        ),
        "eligibility": eligibility,
        "internal": data.get("agent_id") in ELEVENLABS_TEST_AGENT_IDS,
        "source": "elevenlabs",
        "extra_lines": (
            {"ElevenLabs Conversation": conversation_id} if conversation_id else None
        ),
    }


@router.post("/post-call")
async def post_call(request: Request):
    """Post-call webhook -> ONE protocol ticket per call (log_call_core).

    The only async route in the codebase: HMAC verification needs the raw
    request bytes. log_call_core does blocking I/O (requests), so it MUST run
    via run_in_threadpool — inline it would stall the event loop and with it
    the latency-critical Fonio routes.

    Status contract (ElevenLabs retries only 5xx/429/408): unset secret → 503
    (retryable server misconfiguration — queued events survive ~40 min of
    operator fixing); bad signature → 401 (permanent, no retry can fix a
    forgery/mismatched secret); malformed JSON → 400 (permanent); Zammad
    down → 502 from the core (retry creates the ticket later). All parsing
    happens BEFORE the single side effect, so retries never double-create."""
    if not ELEVENLABS_POST_CALL_HMAC_SECRET:
        raise HTTPException(status_code=503, detail="post-call webhook not configured")
    raw = await request.body()
    signature = request.headers.get("elevenlabs-signature")
    if not verify_elevenlabs_signature(
        raw, signature, secret=ELEVENLABS_POST_CALL_HMAC_SECRET
    ):
        # One generic detail for every failure mode (§10.1 spirit); specifics
        # only in server logs.
        log.warning("post-call: signature rejected (header present: %s)", bool(signature))
        raise HTTPException(status_code=401, detail="invalid signature")

    try:
        payload = json.loads(raw)
    except ValueError as e:
        raise HTTPException(status_code=400, detail="invalid JSON") from e

    event_type = payload.get("type") if isinstance(payload, dict) else None
    if event_type != "post_call_transcription":
        # post_call_audio / call_initiation_failure / future types: none of
        # them carry the protocol payload — acknowledge so EL never retries.
        log.info("post-call: ignoring event type %r", event_type)
        return {"status": "ignored"}

    data = payload.get("data") or {}
    conversation_id = data.get("conversation_id") or ""
    if conversation_id:
        cached = _dedup_get(conversation_id)
        if cached is not None:
            log.info("post-call: replay of %s -> cached response", conversation_id)
            return cached

    kwargs = _log_call_kwargs(data)
    result = await run_in_threadpool(log_call_core, **kwargs)
    if conversation_id:
        _dedup_put(conversation_id, result)
    return result
